services:
  - type: web
    name: cliniconex-ai-widget
    env: python
    buildCommand: |
      python -m venv venv
      . venv/bin/activate
      pip install -r requirements.txt
    startCommand: "python app.py"
    envVars:
      - key: OPENAI_API_KEY
        value: your-real-openai-key-here
    pythonVersion: 3.11
